apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dev-ops-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dev-ops-web-app
  template:
    metadata:
      labels:
        app: my-dev-ops-web-app
    spec:
      containers:
      - name: my-dev-ops-web-app
        image: turgutaydemir/my_dev_ops_web_app:turgut_aydemir_1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 400m
            memory: 500Mi
  strategy:
    type: RollingUpdate

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-dev-ops-web-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-dev-ops-web-app
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---

apiVersion: v1
kind: Service
metadata:
  name: my-dev-ops-web-app-service
spec:
  selector:
    app: my-dev-ops-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
