name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Docker
        run: |
          docker pull turgutaydemir/my_dev_ops_web_app:turgut_aydemir_1.1
          docker run -d -p 80:3000 turgutaydemir/my_dev_ops_web_app:turgut_aydemir_1.1
