name: Terraform Workflow

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} >> ~/.aws/credentials
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ~/.aws/credentials
        env:
          AWS_DEFAULT_REGION: us-east-1  # Change to your AWS region

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Cleanup
        run: terraform destroy -auto-approve
